<?php

declare(strict_types = 1);

/**
 * Manual, live-DB smoke test for the Persistence layer (Repository/EntityManager/Mapper) -- see
 * smoke_alias_manager.php's own header for why this isn't part of CI. Run via `console`'s bootstrap so
 * Propel is already configured against the real connection, rather than trying to configure it by hand:
 *
 *   docker exec -w /data -e APPLICATION_ENV=development <container> \
 *     vendor/bin/console orm:model:build ... (not this file directly -- see below)
 *
 * Actually invoked as a standalone script but reusing the project's own Propel runtime config, which
 * `vendor/autoload.php` + a bootstrap of `Propel::init()` from the shop's generated config wires up.
 */

if (!defined('APPLICATION_ENV')) {
    define('APPLICATION_ENV', 'development');
}
if (!defined('APPLICATION_STORE')) {
    define('APPLICATION_STORE', 'DE');
}
if (!defined('APPLICATION_ROOT_DIR')) {
    define('APPLICATION_ROOT_DIR', '/data');
}
if (!defined('APPLICATION_SOURCE_DIR')) {
    define('APPLICATION_SOURCE_DIR', '/data/src');
}
if (!defined('APPLICATION')) {
    define('APPLICATION', 'ZED');
}

require '/data/vendor/autoload.php';

// Triggers Config's lazy singleton init (self-derives APPLICATION_CODE_BUCKET from APPLICATION_STORE as
// a side effect), the same as the real console bootstrap does before any Business/Persistence code runs.
\Spryker\Shared\Config\Config::get('SOME_KEY_THAT_DOES_NOT_EXIST', 'trigger-init-only');

$autoloadPath = '/data/packages/spryker-community/search-index-alias/src';
spl_autoload_register(function (string $class) use ($autoloadPath): void {
    if (!str_starts_with($class, 'SprykerCommunity\\')) {
        return;
    }
    $relative = str_replace('\\', '/', substr($class, strlen('SprykerCommunity\\')));
    $file = $autoloadPath . '/SprykerCommunity/' . $relative . '.php';
    if (!is_file($file)) {
        return;
    }

    require $file;
});

use Generated\Shared\Transfer\SearchIndexMappingDiffTransfer;
use Generated\Shared\Transfer\SearchIndexRolloutTransfer;
use Generated\Shared\Transfer\SearchIndexScopeTransfer;
use SprykerCommunity\Shared\SearchIndexAlias\SearchIndexAliasConfig;
use SprykerCommunity\Zed\SearchIndexAlias\Persistence\Exception\ConcurrentRolloutException;
use SprykerCommunity\Zed\SearchIndexAlias\Persistence\SearchIndexAliasEntityManager;
use SprykerCommunity\Zed\SearchIndexAlias\Persistence\SearchIndexAliasPersistenceFactory;
use SprykerCommunity\Zed\SearchIndexAlias\Persistence\SearchIndexAliasRepository;

// Real generated table map (regenerated by propel:install) -- same one every Zed console command loads.
require '/data/data/cache/propel/generated-conf/loadDatabase.php';

// Connection setup, mirroring Spryker\Zed\Propel\Communication\Plugin\Application\PropelApplicationPlugin
// (which normally reads these same values via Config::get() from the project's env-driven config files)
// but built directly from the known SPRYKER_DB_* container env, to avoid bootstrapping this whole
// script through Spryker's full Config layer just for a one-off smoke test.
$manager = new \Propel\Runtime\Connection\ConnectionManagerSingle('zed');
$manager->setConfiguration([
    'dsn' => sprintf(
        'mysql:host=%s;port=%s;dbname=%s;charset=utf8',
        getenv('SPRYKER_DB_HOST') ?: 'database',
        getenv('SPRYKER_DB_PORT') ?: '3306',
        getenv('SPRYKER_DB_DATABASE') ?: 'eu-docker',
    ),
    'user' => getenv('SPRYKER_DB_USERNAME') ?: 'spryker',
    'password' => getenv('SPRYKER_DB_PASSWORD') ?: 'secret',
]);
$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->setAdapterClass('zed', 'mysql');
$serviceContainer->setConnectionManager($manager);
$serviceContainer->setDefaultDatasource('zed');

$entityManager = new SearchIndexAliasEntityManager();
$entityManager->setFactory(new SearchIndexAliasPersistenceFactory());
$repository = new SearchIndexAliasRepository();
$repository->setFactory(new SearchIndexAliasPersistenceFactory());

function line(string $label, callable $fn): void
{
    echo str_pad($label, 65, '.');
    try {
        $result = $fn();
        echo ' OK ' . ($result !== null ? '(' . (is_array($result) ? json_encode($result) : $result) . ')' : '') . "\n";
    } catch (Throwable $e) {
        echo ' FAIL: ' . $e::class . ': ' . $e->getMessage() . "\n";
    }
}

// cleanup from any previous run
$existing = $repository->getRolloutHistoryForScope('smoke_source', 'SMOKE');
foreach ($existing as $searchIndexRolloutTransfer) {
    \Orm\Zed\SearchIndexAlias\Persistence\SpySearchIndexRolloutQuery::create()
        ->filterByIdSearchIndexRollout($searchIndexRolloutTransfer->getIdSearchIndexRollout())
        ->delete();
}

echo "=== SearchIndexAlias Persistence smoke test against live MySQL ===\n";

$scope = (new SearchIndexScopeTransfer())
    ->setSourceIdentifier('smoke_source')
    ->setStoreName('SMOKE')
    ->setAliasName('smoke_source_smoke');

$firstRolloutId = null;

line('createRollout(status=building)', function () use ($entityManager, $scope, &$firstRolloutId) {
    $transfer = (new SearchIndexRolloutTransfer())
        ->setSearchIndexScope($scope)
        ->setStatus(SearchIndexAliasConfig::STATUS_BUILDING)
        ->setLiveIndexName('smoke_source_smoke_20260101_000000')
        ->setTriggeredByUser('smoke-test');

    $saved = $entityManager->createRollout($transfer);
    $firstRolloutId = $saved->getIdSearchIndexRollout();

    return 'id=' . $firstRolloutId;
});

line('findActiveRolloutForScope() -> finds the BUILDING row', function () use ($repository) {
    $active = $repository->findActiveRolloutForScope('smoke_source', 'SMOKE');

    return $active === null ? 'NULL -- BUG' : 'status=' . $active->getStatus();
});

line('createRollout() again for the SAME scope -> DB-enforced refusal', function () use ($entityManager, $scope) {
    $transfer = (new SearchIndexRolloutTransfer())
        ->setSearchIndexScope($scope)
        ->setStatus(SearchIndexAliasConfig::STATUS_BUILDING);

    try {
        $entityManager->createRollout($transfer);
    } catch (ConcurrentRolloutException) {
        return 'correctly refused (unique index)';
    }

    return 'DID NOT THROW -- BUG';
});

line('updateRollout() to a terminal status clears active_scope_key', function () use ($entityManager, $repository) {
    $active = $repository->findActiveRolloutForScope('smoke_source', 'SMOKE');
    $active->setStatus(SearchIndexAliasConfig::STATUS_FLIPPED)
        ->setTargetIndexName('smoke_source_smoke_20260815_120000')
        ->setOutcome('flipped to smoke_source_smoke_20260815_120000')
        ->setSearchIndexMappingDiff(
            (new SearchIndexMappingDiffTransfer())
                ->setClassification(SearchIndexAliasConfig::MAPPING_DIFF_ADDITIVE)
                ->setAddedFields(['new-field'])
                ->setBreakingFields([]),
        );
    $entityManager->updateRollout($active);

    $stillActive = $repository->findActiveRolloutForScope('smoke_source', 'SMOKE');

    return $stillActive === null ? 'correctly cleared' : 'STILL ACTIVE -- BUG';
});

line('createRollout() for the SAME scope NOW succeeds (prior one is terminal)', function () use ($entityManager, $scope) {
    $transfer = (new SearchIndexRolloutTransfer())
        ->setSearchIndexScope($scope)
        ->setStatus(SearchIndexAliasConfig::STATUS_BUILDING)
        ->setTriggeredByUser('smoke-test-2');

    $saved = $entityManager->createRollout($transfer);

    return 'id=' . $saved->getIdSearchIndexRollout();
});

line('getRolloutHistoryForScope() -> 2 rows, newest first', function () use ($repository) {
    $history = $repository->getRolloutHistoryForScope('smoke_source', 'SMOKE');
    $statuses = array_map(fn ($t) => $t->getStatus(), $history);

    return count($history) === 2 ? implode(',', $statuses) : 'WRONG COUNT: ' . count($history);
});

line('mapping diff round-trips correctly through the terminal row', function () use ($repository) {
    $history = $repository->getRolloutHistoryForScope('smoke_source', 'SMOKE');
    $flipped = null;
    foreach ($history as $searchIndexRolloutTransfer) {
        if ($searchIndexRolloutTransfer->getStatus() !== SearchIndexAliasConfig::STATUS_FLIPPED) {
            continue;
        }

        $flipped = $searchIndexRolloutTransfer;
    }
    if ($flipped === null) {
        return 'FLIPPED ROW NOT FOUND -- BUG';
    }
    $diff = $flipped->getSearchIndexMappingDiff();
    if ($diff === null || $diff->getClassification() !== SearchIndexAliasConfig::MAPPING_DIFF_ADDITIVE) {
        return 'MAPPING DIFF MISMATCH -- BUG';
    }
    if ($diff->getAddedFields() !== ['new-field']) {
        return 'ADDED FIELDS MISMATCH: ' . json_encode($diff->getAddedFields());
    }

    return 'classification=' . $diff->getClassification() . ' addedFields=' . json_encode($diff->getAddedFields());
});

line('getLatestRolloutPerScope() includes our scope exactly once, as the BUILDING row', function () use ($repository) {
    $latest = $repository->getLatestRolloutPerScope();
    $ours = array_values(array_filter(
        $latest,
        fn ($t) => $t->getSearchIndexScope()->getSourceIdentifier() === 'smoke_source'
            && $t->getSearchIndexScope()->getStoreName() === 'SMOKE',
    ));

    if (count($ours) !== 1) {
        return 'WRONG COUNT for our scope: ' . count($ours) . ' (total latest rows: ' . count($latest) . ')';
    }

    return 'status=' . $ours[0]->getStatus();
});

// cleanup
echo "\n=== cleanup ===\n";
$history = $repository->getRolloutHistoryForScope('smoke_source', 'SMOKE');
foreach ($history as $searchIndexRolloutTransfer) {
    \Orm\Zed\SearchIndexAlias\Persistence\SpySearchIndexRolloutQuery::create()
        ->filterByIdSearchIndexRollout($searchIndexRolloutTransfer->getIdSearchIndexRollout())
        ->delete();
    echo 'deleted rollout id ' . $searchIndexRolloutTransfer->getIdSearchIndexRollout() . "\n";
}
echo "done.\n";
